name: üöÄ Provisionar Banco PostgreSQL (manual + IP customizado)

on:
  workflow_dispatch:
    inputs:
      allowed_ip:
        description: "Endere√ßo IP autorizado a acessar o PostgreSQL (ex: 201.10.22.55)"
        required: true
        default: "0.0.0.0"

permissions:
  contents: read
  id-token: write

jobs:
  terraform:
    name: "Provisionar Banco (Dev)"
    runs-on: ubuntu-latest

    env:
      ARM_USE_OIDC: true
      ARM_USE_AZUREAD: true
      TF_IN_AUTOMATION: true
      ENV_PATH: envs/dev
      BACKEND_PATH: backend/dev.backend.tfvars
      TF_VAR_pg_password: ${{ secrets.TF_VAR_pg_password }}
    steps:
      # 1Ô∏è‚É£ Checkout do c√≥digo
      - name: Checkout
        uses: actions/checkout@v4

      # 2Ô∏è‚É£ Setup do Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.0

      # 3Ô∏è‚É£ Login no Azure via OIDC
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # 4Ô∏è‚É£ Inicializa o Terraform
      - name: Terraform Init
        run: terraform -chdir=${{ env.ENV_PATH }} init -backend-config="../../${{ env.BACKEND_PATH }}" -reconfigure

      # 5Ô∏è‚É£ Plano com IP din√¢mico
      - name: Terraform Plan
        run: terraform -chdir=${{ env.ENV_PATH }} plan -out=plan.out -var="allowed_ip=${{ github.event.inputs.allowed_ip }}"

      # 6Ô∏è‚É£ Aplica√ß√£o do plano
      - name: Terraform Apply
        run: terraform -chdir=${{ env.ENV_PATH }} apply -auto-approve plan.out
